DROP TABLE IF EXISTS `file`;
CREATE TABLE `file`  (
  `id` int(0) NOT NULL,
  `title` varchar(255) CHARACTER SET utf8  NOT NULL,
  `file` varchar(255) CHARACTER SET utf8  NULL DEFAULT NULL,
  `file_cut` varchar(255) CHARACTER SET utf8  NULL DEFAULT NULL,
  `description` varchar(4000) CHARACTER SET utf8  NULL DEFAULT NULL,
  `image` varchar(500) CHARACTER SET utf8  NULL DEFAULT NULL,
  `attachment` varchar(500) CHARACTER SET utf8  NULL DEFAULT NULL,
  `author_id` int(0) NOT NULL,
  `approver_id` int(0) NULL DEFAULT NULL,
  `delete_id` int(0) NULL DEFAULT NULL,
  `is_vip` BOOLEAN,
  `is_deleted` tinyint(0) NULL DEFAULT NULL,
  `rating` float NULL DEFAULT NULL,
  `reading` int(0) NULL DEFAULT NULL,
  `dowloading` int(0) NULL DEFAULT NULL,
  `total_comment` int(0) NULL DEFAULT NULL,
  `total_like` int(0) NULL DEFAULT NULL,
  `like` BOOLEAN ,
  `card` BOOLEAN ,
  `view` int(0) NULL DEFAULT NULL,
  `start_page_number` int(0) NULL DEFAULT NULL,
  `end_page_number` int(0) NULL DEFAULT NULL,
  `total_page_number` int(0) NULL DEFAULT NULL,
  `created_date` datetime(0) NULL DEFAULT NULL,
  `updated_date` datetime(0) NULL DEFAULT NULL,
  `approved_date` datetime(0) NULL DEFAULT NULL,
  `delete_date` datetime(0) NULL DEFAULT NULL,
  `file_group` int(0) NULL DEFAULT NULL,
  `language_id` int(0) NULL DEFAULT NULL,
  `category_id` int(0) NULL DEFAULT NULL,
  `school_id` int(0) NULL DEFAULT NULL,
  `specialization_id` int(0) NULL DEFAULT NULL,
  `industry_id` int(0) NULL DEFAULT NULL,
  `file_hashcode` varchar(500) NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
);
